apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: srotas-networking
  namespace: argocd
spec:
  project: srotas
  source:
    repoURL: <REPO_URL>
    targetRevision: main
    path: srotas/networking
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
