apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: postgres   # create a StatefulSet later or repoint to externalIP
  ports:
  - port: 5432
    targetPort: 5432
