apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: apps
spec:
  type: ClusterIP
  selector:
    app: redis      # create a Deployment/StatefulSet later or repoint to externalIP
  ports:
  - port: 6379
    targetPort: 6379
