apiVersion: v1
kind: Service
metadata:
  name: srotas-main
  namespace: apps
  labels: 
    app: srotas-main
    app.kubernetes.io/part-of: srotas
    service: main
    owner: xsm
spec:
  type: ClusterIP
  selector: {app: srotas-main}
  ports:
    - name: http
      port: 8080
      targetPort: 8080