apiVersion: v1
kind: Service
metadata:
  name: srotas-fe
  namespace: apps
  labels:
    app: srotas-fe
    app.kubernetes.io/part-of: srotas
spec:
  selector:
    app: srotas-fe
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  type: ClusterIP
