apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: redis-auth
  namespace: apps
spec:
  refreshInterval: 1m
  target:
    name: redis-auth
    creationPolicy: Owner
  data:
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: srotas-dev-secrets
        property: REDIS_PASSWORD
  secretStoreRef:
    kind: ClusterSecretStore
    name: local-kubernetes
