apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: srotas-main-env
  namespace: apps
spec:
  refreshInterval: 1m
  target:
    name: srotas-main-env
    creationPolicy: Owner
  data:
    # Local dev via local-kubernetes provider
    - secretKey: DATABASE_URL
      remoteRef:
        key: srotas-dev-secrets
        property: DATABASE_URL
    - secretKey: POSTGRES_USER
      remoteRef:
        key: srotas-dev-secrets
        property: POSTGRES_USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: srotas-dev-secrets
        property: POSTGRES_PASSWORD

  # Switch to AWS by changing this storeRef to 'aws-asm' and mapping ASM keys
  # for example:
  # data:
  #   - secretKey: DATABASE_URL
  #     remoteRef:
  #       key: srotas/prod/database_url
  #   - secretKey: POSTGRES_USER
  #     remoteRef:
  #       key: srotas/prod/postgres_user
  #   - secretKey: POSTGRES_PASSWORD
  #     remoteRef:
  #       key: srotas/prod/postgres_password

  # Default store for this ExternalSecret
  # (can be overridden per key by specifying remoteRef.remoteNamespace/kind)
  secretStoreRef:
    kind: ClusterSecretStore
    name: local-kubernetes
