apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: local-kubernetes
spec:
  provider:
    kubernetes:
      remoteNamespace: secrets
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          namespace: default
          key: ca.crt
      auth:
        serviceAccount:
          name: default
          namespace: apps
