apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-asm
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        # Local / simple: use access keys from a Secret (namespace external-secrets)
        secretRef:
          accessKeyIDSecretRef:
            name: aws-creds
            namespace: external-secrets
            key: access-key
          secretAccessKeySecretRef:
            name: aws-creds
            namespace: external-secrets
            key: secret-access-key
        # For EKS IRSA, replace the 'secretRef' block with:
        # serviceAccountRef:
        #   name: external-secrets
        #   namespace: external-secrets
