# /Users/xsm/Documents/workspace/AWS/eks/projects/srotas/argocd/webhook-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  namespace: argocd
type: Opaque
stringData:
  webhook.github.secret: <path:secret/data/srotas/argocd/webhook#github-secret>
