apiVersion: v1
kind: Namespace
metadata:
  name: apps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srotas-echo
  namespace: apps
spec:
  replicas: 1
  selector:
    matchLabels: { app: srotas-echo }
  template:
    metadata:
      labels: { app: srotas-echo }
    spec:
      containers:
        - name: echo
          image: hashicorp/http-echo:1.0.0
          args: ["-text=Hello from srotas-echo"]
          ports:
            - containerPort: 5678
          readinessProbe:
            httpGet: { path: "/", port: 5678 }
            initialDelaySeconds: 2
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: srotas-echo
  namespace: apps
spec:
  selector: { app: srotas-echo }
  ports:
    - name: http
      port: 8080
      targetPort: 5678
