# /Users/xsm/Documents/workspace/AWS/eks/projects/srotas/argocd/apps/networking/srotas-networking.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: srotas-networking
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/xsmmaurya/eks.git
    targetRevision: main
    path: srotas/networking          # <- adjust if your folder differs
  destination:
    server: https://kubernetes.default.svc
    namespace: networking
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 2
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m
  revisionHistoryLimit: 3
